hwi_oauth:
    firewall_names: [main]

    fosub:
        username_iterations: 30
        properties:
            twitter: twitterId

    resource_owners:
        twitter:
            type:                twitter
            client_id:           '%twitter.client_id%'
            client_secret:       '%twitter.client_secret%'
            options:
                include_email: true
