# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_provider:
            entity:
                class: AppBundle:User
                property: email

    # ...

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/admin
            http_basic: ~
            provider: database_provider
            logout: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_USER }

    role_hierarchy:
        ROLE_TWITTER_ADMIN:
            - ROLE_USER
            - ROLE_APP_ADMIN_CITY_TWITTER
            - ROLE_APP_ADMIN_TWITTER_SCHEDULE_ALL
        ROLE_CITY_ADMIN:
            - ROLE_USER
            - ROLE_APP_ADMIN_CITY_ALL
        ROLE_STATION_ADMIN:
            - ROLE_USER
            - ROLE_APP_ADMIN_STATION_ALL
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_TWITTER_MANAGER
            - ROLE_CITY_MANAGER
            - ROLE_STATION_MANAGER
            - ROLE_APP_ADMIN_USER_ALL
        ROLE_USER:
            - ROLE_APP_ADMIN_CITY_LIST
            - ROLE_APP_ADMIN_CITY_VIEW
            - ROLE_APP_ADMIN_STATION_LIST
            - ROLE_APP_ADMIN_STATION_VIEW
            - ROLE_APP_ADMIN_TWITTER_SCHEDULE_LIST
            - ROLE_APP_ADMIN_TWITTER_SCHEDULE_VIEW
            - ROLE_APP_ADMIN_USER_LIST
            - ROLE_APP_ADMIN_USER_VIEW

    access_decision_manager:
        strategy: unanimous
